import "./globals.css";
import Hero from "./hero/hero";
import Navbar from "./navbar/navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-stone-100 ">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
